Add a policy for blacklisting GATT UUIDs.
WebBluetoothCG/registries pull request #16
Opened 2016-09-17 00:01 UTC by jyasskin

Fixes #10, fixes WebBluetoothCG/web-bluetooth#258.

@beaufortfrancois @gfwilliams

2016-09-19 08:08 UTC, beaufortfrancois commented on gatt_blacklist_policy.md
> +when the issue is filed and when the new UUID is added to the blacklist.
Should we mention the finch blacklist that allows Chrome to deploy very quickly in case of an emergency?

2016-09-19 08:10 UTC, beaufortfrancois requested changes
LGTM but nit

2016-09-19 17:52 UTC, jyasskin commented on gatt_blacklist_policy.md
> +when the issue is filed and when the new UUID is added to the blacklist.
How's this? I don't really want to mention Chrome specifically, but all implementations should have some way to push these changes quickly.

2016-09-20 07:44 UTC, beaufortfrancois approved these changes
LGTM

2016-09-26 23:30 UTC, merged